name: Build and Upload JAR

on:
  push:
    branches:
        - main
        - 'release/*'
        - 'ci/*' # TODO : remove later
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: uf-api-jar
          path: target/*.jar

# TODO : to update when the server is ready
#      - name: Upload JAR on my server
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USER: ${{ secrets.SSH_USER }}
#        run: |
#          echo "$SSH_PRIVATE_KEY" > private_key.pem
#          chmod 600 private_key.pem
#          scp -i private_key.pem target/*.jar $SSH_USER@$SSH_HOST:/path/to/destination/
#          rm private_key.pem
